SELECT RPAD('Soleil',17,'bla') "RPAD exemple" FROM DUAL;
SELECT LPAD('Master 2 EID',15,'.*') "LPAD exemple" FROM DUAL;
SELECT SUBSTR('DESS EID',6,3) "SUBSTR exemple" FROM DUAL;
SELECT SUBSTR('ABCDEFGHIJ',-5,4) "SUBSTR exemple" FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS') "Now" FROM DUAL;
SELECT LENGTH('WEB WARHOUSE') "Longueur en caractères" FROM DUAL;
SELECT ROUND(17.0958,1) "ROUND exemple" FROM DUAL;
SELECT ROUND(17.58,2) "ROUND exemple" FROM DUAL;
SELECT TRUNC(1958.0917,1) "TRUNC exemple" FROM DUAL;
SELECT TRUNC(1958.0917,2) "TRUNC exemple" FROM DUAL;
SELECT ROUND(TO_DATE('SEP-17-2009'),'YEAR') "New Year" FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,7) FROM DUAL;
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE('JUN-19-2001'))) AS AGEBB FROM DUAL;
SELECT TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
