SELECT * FROM PERSONNES ORDER BY datenaissance;

/* 3 */
SELECT NUMERO,NOM,PRENOM,PERE,MERE FROM PERSONNES WHERE NUMERO != 7
START WITH NUMERO = 7
CONNECT BY NUMERO = PRIOR MERE OR NUMERO = PRIOR PERE;
/* 4 */
DROP VIEW PERE;
DROP VIEW GRAND_PERE;
DROP VIEW ARRIERE_GRAND_PERE;
CREATE VIEW PERE(PERE) AS (SELECT PERE FROM PERSONNES P WHERE P.NUMERO = 10);
CREATE VIEW GRAND_PERE(PERE) AS (SELECT PERE FROM PERSONNES P WHERE P.NUMERO IN (SELECT PERE FROM PERE));
CREATE VIEW ARRIERE_GRAND_PERE(PERE) AS (SELECT PERE FROM PERSONNES P WHERE P.NUMERO IN (SELECT PERE FROM GRAND_PERE));
SELECT * FROM PERE;
SELECT * FROM GRAND_PERE;
SELECT * FROM ARRIERE_GRAND_PERE;
SELECT * FROM PERSONNES WHERE NUMERO IN (SELECT PERE FROM PERE) OR NUMERO IN (SELECT PERE FROM GRAND_PERE) OR NUMERO IN (SELECT PERE FROM ARRIERE_GRAND_PERE);
/* 5 */
SELECT DISTINCT NUMERO,NOM,PRENOM FROM PERSONNES WHERE NUMERO != 98
START WITH NUMERO = 98
CONNECT BY PRIOR NUMERO = MERE OR PRIOR NUMERO = PERE;
/* 6 */
SELECT P2.NUMERO,P2.NOM,P2.PRENOM,P1.MERE,P1.PERE FROM PERSONNES P1,PERSONNES P2 WHERE P1.NUMERO = 8 AND P1.MERE = P2.MERE AND P1.PERE = P2.PERE AND P1.NUMERO != P2.NUMERO;
/* 7 */
SELECT P2.NUMERO,P2.NOM,P2.PRENOM,P1.MERE,P1.PERE FROM PERSONNES P1,PERSONNES P2 WHERE P1.NUMERO = 7 AND P1.MERE = P2.MERE AND P1.PERE = P2.PERE AND P1.NUMERO != P2.NUMERO AND P2.SEXE = 'F';
/* 8 */
DROP VIEW TEST;
CREATE VIEW TEST(NUMERO,PERE,MERE) AS (SELECT NUMERO,PERE,MERE FROM PERSONNES WHERE SEXE = 'F' AND EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM DATENAISSANCE) > 40);
SELECT * FROM TEST;
SELECT * FROM PERSONNES P WHERE P.MERE IN (SELECT NUMERO FROM TEST);
/* 9 */
DROP VIEW PARENTS;
DROP VIEW ONCLES_TANTES;
CREATE VIEW PARENTS(NUMERO,PERE,MERE) AS (SELECT P2.NUMERO,P2.PERE,P2.MERE FROM PERSONNES P1,PERSONNES P2 WHERE (P1.NUMERO = 8 AND P1.NUMERO != P2.NUMERO) AND (P1.PERE = P2.NUMERO OR P1.MERE = P2.NUMERO));
CREATE VIEW ONCLES_TANTES(NUMERO) AS (SELECT NUMERO FROM PERSONNES P WHERE (P.MERE IN (SELECT MERE FROM PARENTS) OR P.PERE IN (SELECT PERE FROM PARENTS)) AND P.NUMERO NOT IN (SELECT NUMERO FROM PARENTS));
SELECT * FROM PARENTS;
SELECT * FROM ONCLES_TANTES;
SELECT * FROM PERSONNES P WHERE P.PERE IN (SELECT NUMERO FROM ONCLES_TANTES) OR P.MERE IN (SELECT NUMERO FROM ONCLES_TANTES);
/* 10 */






/* 11 */
DROP VIEW MAX_AGE;
DROP VIEW ENFANTS;
CREATE VIEW MAX_AGE(NUMERO) AS (SELECT NUMERO FROM PERSONNES WHERE DATENAISSANCE = (SELECT MIN(DATENAISSANCE) FROM PERSONNES));
CREATE VIEW ENFANTS(NUMERO) AS (SELECT NUMERO FROM PERSONNES P WHERE P.PERE IN (SELECT NUMERO FROM MAX_AGE) OR P.MERE IN (SELECT NUMERO FROM MAX_AGE));
SELECT * FROM MAX_AGE;
SELECT * FROM ENFANTS;
SELECT NUMERO FROM PERSONNES P WHERE P.PERE IN (SELECT NUMERO FROM ENFANTS) OR P.MERE IN (SELECT NUMERO FROM ENFANTS);
/* 12 */










































