ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

ALTER TABLE CHARGE ADD CONSTRAINT FK_PROFESSEURS_NUM_CHARGE FOREIGN KEY (NUM_PROF) REFERENCES PROFESSEURS(NUM_PROF);
ALTER TABLE CHARGE ADD CONSTRAINT FK_COURS_NUM_CHARGE FOREIGN KEY (NUM_COURS) REFERENCES COURS(NUM_COURS);
ALTER TABLE RESULTATS ADD CONSTRAINT FK_ELEVES_NUM_RESULTATS FOREIGN KEY (NUM_ELEVE) REFERENCES ELEVES(NUM_ELEVE);
ALTER TABLE RESULTATS ADD CONSTRAINT FK_COURS_NUM_RESULTATS FOREIGN KEY (NUM_COURS) REFERENCES COURS(NUM_COURS);
ALTER TABLE ACTIVITES_PRATIQUEES ADD CONSTRAINT PK_ELEVES_NUM_AP FOREIGN KEY (NUM_ELEVE) REFERENCES ELEVES(NUM_ELEVE);
ALTER TABLE ACTIVITES_PRATIQUEES ADD CONSTRAINT FK_ACTIVITE_AP FOREIGN KEY (NIVEAU,NOM) REFERENCES ACTIVITES(NIVEAU,NOM);

DESC ELEVES;

ALTER TABLE ELEVES ADD (
	CODEPOSTAL		NUMBER(5),
	VILLE			VARCHAR2(20)
);

DESC ELEVES;

UPDATE ELEVES SET CODEPOSTAL = 75013, VILLE = 'paris' WHERE NUM_ELEVE = 1;		
UPDATE ELEVES SET CODEPOSTAL = 93800, VILLE = 'EPINAY / seine' WHERE NUM_ELEVE = 2;
UPDATE ELEVES SET CODEPOSTAL = 93430, VILLE = 'EPINAY SUR SEINE' WHERE NUM_ELEVE = 5;
UPDATE ELEVES SET CODEPOSTAL = 91000, VILLE = 'EPINAY / ORGE' WHERE NUM_ELEVE = 7;

SELECT * FROM ELEVES;

CREATE TABLE AGGLOMERATION(
	CP		NUMBER(5),
	VILLE		VARCHAR2(25)
);

DESC AGGLOMERATION;

ALTER TABLE AGGLOMERATION ADD CONSTRAINT PK_AGGLOMERATION PRIMARY KEY (CP,VILLE);
ALTER TABLE AGGLOMERATION ADD CONSTRAINT CK_VILLE_AGGLOMERATION CHECK(VILLE=UPPER(VILLE));

select constraint_name from user_constraints where table_name='AGGLOMERATION';

INSERT INTO AGGLOMERATION VALUES(75001,'PARIS');
INSERT INTO AGGLOMERATION VALUES(75013,'PARIS');
INSERT INTO AGGLOMERATION VALUES(93800,'EPINAY SUR SEINE');
INSERT INTO AGGLOMERATION VALUES(93430,'villetaneuse');
INSERT INTO AGGLOMERATION VALUES(91000,'EPINAY SUR ORGE');
INSERT INTO AGGLOMERATION VALUES(93800,'EPINAY / SEINE');

SELECT * FROM AGGLOMERATION;

UPDATE ELEVES SET VILLE = (SELECT VILLE FROM AGGLOMERATION WHERE CODEPOSTAL = CP AND ROWNUM = 1);

SELECT * FROM ELEVES;
