ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
SELECT * FROM ELEVES;
SELECT * FROM PROFESSEURS;
SELECT * FROM COURS;
SELECT * FROM RESULTATS;
SELECT * FROM ACTIVITES;
SELECT * FROM ACTIVITES_PRATIQUEES;
SELECT NOM,PRENOM,DATE_NAISSANCE FROM ELEVES;
SELECT * FROM ACTIVITES;
SELECT SPECIALITE FROM PROFESSEURS;
SELECT NOM,PRENOM FROM ELEVES WHERE POIDS < 45 AND ANNEE BETWEEN 1 AND 2;
SELECT NOM FROM ELEVES WHERE POIDS BETWEEN 60 AND 80;
SELECT NOM FROM PROFESSEURS WHERE SPECIALITE = 'poésie' OR SPECIALITE = 'sql';
SELECT NOM FROM ELEVES WHERE NOM LIKE 'L%';
SELECT NOM FROM PROFESSEURS WHERE SPECIALITE IS NULL;
SELECT NOM,PRENOM FROM ELEVES WHERE POIDS < 45 AND ANNEE = 1;
SELECT NOM,DECODE(SPECIALITE,NULL,'****',SPECIALITE) AS SPECIALITE FROM PROFESSEURS;
/* 11 */
SELECT E.NOM,E.PRENOM FROM (ELEVES E JOIN ACTIVITES_PRATIQUEES A USING(Num_eleve)) WHERE (NIVEAU = 1 AND A.NOM = 'Surf');
SELECT E.NOM,E.PRENOM FROM ((SELECT * FROM ACTIVITES_PRATIQUEES WHERE NIVEAU = 1 AND NOM = 'Surf') JOIN ELEVES E USING(NUM_ELEVE));
SELECT E.NOM,E.PRENOM FROM ((SELECT * FROM ACTIVITES_PRATIQUEES WHERE NIVEAU IN (1) AND NOM IN ('Surf')) JOIN ELEVES E USING(NUM_ELEVE));
SELECT E.NOM,E.PRENOM FROM (((SELECT * FROM ACTIVITES_PRATIQUEES) MINUS (SELECT * FROM ACTIVITES_PRATIQUEES WHERE NIVEAU != 1 OR NOM != 'Surf')) JOIN ELEVES E USING(NUM_ELEVE));
SELECT E.NOM,E.PRENOM FROM (((SELECT * FROM ACTIVITES_PRATIQUEES) INTERSECT (SELECT * FROM ACTIVITES_PRATIQUEES WHERE NIVEAU IN (1) AND NOM IN ('Surf'))) JOIN ELEVES E USING(NUM_ELEVE));
/* 12 */
SELECT E.NOM FROM ((ACTIVITES_PRATIQUEES AP JOIN ACTIVITES A USING(Niveau,Nom)) JOIN ELEVES E USING(Num_eleve)) WHERE EQUIPE = 'Amc Indus';
SELECT E.NOM FROM ((SELECT * FROM ACTIVITES A WHERE EQUIPE IN ('Amc Indus')) JOIN ACTIVITES_PRATIQUEES AP USING(NOM,NIVEAU)) JOIN ELEVES E USING(NUM_ELEVE);
/* 13 */
SELECT P1.NOM,P2.NOM FROM PROFESSEURS P1, PROFESSEURS P2 WHERE (P1.SPECIALITE = P2.SPECIALITE AND P1.NUM_PROF != P2.NUM_PROF);
/* 14 */
SELECT NOM,SALAIRE_ACTUEL,SALAIRE_ACTUEL-SALAIRE_BASE AS AUGMENTATION FROM PROFESSEURS WHERE SPECIALITE = 'sql';
SELECT NOM,SALAIRE_ACTUEL,SALAIRE_ACTUEL-SALAIRE_BASE AS AUGMENTATION FROM PROFESSEURS WHERE SPECIALITE IN ('sql');
/* 15 */
SELECT NOM FROM PROFESSEURS WHERE SALAIRE_ACTUEL-SALAIRE_BASE > 0.25*SALAIRE_BASE;
SELECT NOM FROM PROFESSEURS WHERE SALAIRE_ACTUEL-SALAIRE_BASE != 0 AND SALAIRE_ACTUEL-SALAIRE_BASE BETWEEN 0 AND 0.25*SALAIRE_BASE;
/* 16 */
SELECT 4*POINTS AS POINTS_SUR_100 FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) WHERE NUM_ELEVE = 5;
SELECT 4*R.POINTS AS POINTS_SUR_100 FROM ((SELECT * FROM RESULTATS) MINUS (SELECT * FROM RESULTATS WHERE NUM_ELEVE != 5)) R;
/* 17 */
SELECT AVG(POIDS) AS POIDS_MOYEN_AN1 FROM ELEVES WHERE ANNEE = 1;
SELECT AVG(POIDS) AS POIDS_MOYEN_AN1 FROM ((SELECT * FROM ELEVES) MINUS (SELECT * FROM ELEVES WHERE ANNEE != 1));
/* 18 */
SELECT SUM(POINTS) AS POINT_TOTAL FROM RESULTATS WHERE NUM_ELEVE = 3;
SELECT SUM(POINTS) AS POINT_TOTAL FROM ((SELECT * FROM RESULTATS) INTERSECT (SELECT * FROM RESULTATS WHERE NUM_ELEVE = 3));
/* 19 */
SELECT MIN(POINTS) AS MINIMUN, MAX(POINTS) AS MAXIMUM FROM RESULTATS WHERE NUM_ELEVE = 1;
SELECT MIN(POINTS) AS MINIMUN, MAX(POINTS) AS MAXIMUM FROM RESULTATS WHERE NUM_ELEVE IN (1);
/* 20 */
SELECT COUNT(*) AS NB_ELEVES_AN2 FROM ELEVES GROUP BY ANNEE HAVING ANNEE = 2;
SELECT COUNT(*) AS NB_ELEVES_AN2 FROM ELEVES WHERE ANNEE = 2;
/* 21 */
SELECT AVG(SALAIRE_ACTUEL-SALAIRE_BASE) AS MOYENNE_AUGMENTATION FROM PROFESSEURS WHERE SPECIALITE = 'sql';
SELECT AVG(SALAIRE_ACTUEL-SALAIRE_BASE) AS MOYENNE_AUGMENTATION FROM PROFESSEURS WHERE SPECIALITE IN ('sql');
/* 22 */
SELECT EXTRACT(YEAR FROM Der_prom) AS ANNEE_DER_PROM FROM PROFESSEURS WHERE NUM_PROF = 8;
/* 23 */
SELECT Date_entree,Der_prom,EXTRACT(YEAR FROM Der_prom)-EXTRACT(YEAR FROM Date_entree) AS ANNEE_PASSEE FROM PROFESSEURS;
/* 24 */
SELECT AVG(EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM date_naissance)) AS AGE_MOYEN FROM ELEVES;
/* 25 */
SELECT NOM FROM PROFESSEURS WHERE ADD_MONTHS(Date_entree,50) < Der_prom;
/* 26 */
SELECT NOM FROM ELEVES WHERE EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,4)) - EXTRACT(YEAR FROM date_naissance) > 24;
/* 27 */
SELECT * FROM ELEVES ORDER BY ANNEE,NOM;
/* 28 */
SELECT 4*POINTS AS POINTS_SUR_100 FROM RESULTATS WHERE NUM_ELEVE = 5 ORDER BY 4*POINTS DESC;
SELECT 4*POINTS AS POINTS_SUR_100 FROM ((SELECT * FROM RESULTATS) MINUS (SELECT * FROM RESULTATS WHERE NUM_ELEVE != 5)) ORDER BY 4*POINTS DESC;
/* 29 */
SELECT NOM,AVG(POINTS) AS MOYENNE FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) WHERE ANNEE = 1 GROUP BY NOM;
/* 30 */
SELECT NUM_ELEVE,AVG(POINTS) AS MOYENNE FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) WHERE ANNEE = 1 GROUP BY NUM_ELEVE HAVING SUM(POINTS) > 40;
/* 31 */
SELECT MAX(POINT_TOTAL) AS MAXIMUM FROM (SELECT SUM(POINTS) AS POINT_TOTAL FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) GROUP BY NUM_ELEVE);
/* 32 */
SELECT E.NOM FROM ((ACTIVITES_PRATIQUEES AP JOIN ACTIVITES USING(NIVEAU,NOM)) JOIN ELEVES E USING(NUM_ELEVE)) WHERE EQUIPE = 'Amc Indus';
/* 33 */
SELECT AVG(POINTS) AS MOYENNE FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) WHERE ANNEE = 1 GROUP BY NUM_ELEVE HAVING AVG(POINTS) > (SELECT AVG(POINTS) AS MOYENNE FROM (RESULTATS JOIN ELEVES USING(NUM_ELEVE)) GROUP BY ANNEE HAVING ANNEE = 1);
/* 34 */
SELECT E1.NOM,E1.POIDS FROM ELEVES E1 WHERE ANNEE = 1 GROUP BY NOM,POIDS HAVING E1.POIDS > (SELECT MAX(POIDS) FROM ELEVES E2 WHERE ANNEE = 2);
SELECT E1.NOM,E1.POIDS FROM ELEVES E1 WHERE ANNEE = 1 AND NOT EXISTS (SELECT E2.NOM,E2.POIDS FROM ELEVES E2 WHERE E1.POIDS < E2.POIDS) GROUP BY NOM,POIDS;
/* 35 */
SELECT E1.NOM,E1.POIDS FROM ELEVES E1 WHERE ANNEE = 1 GROUP BY NOM,POIDS HAVING E1.POIDS > (SELECT MIN(POIDS) FROM ELEVES E2 WHERE ANNEE = 2);
SELECT E1.NOM,E1.POIDS FROM ELEVES E1 WHERE ANNEE = 1 AND E1.POIDS > ANY (SELECT E2.POIDS FROM ELEVES E2 WHERE ANNEE = 2);
/* 36 */
SELECT NOM,POIDS,ANNEE FROM ELEVES E1 WHERE E1.POIDS > (SELECT AVG(POIDS) FROM ELEVES E2 WHERE E2.ANNEE = E1.ANNEE);
/* 37 */
SELECT NOM FROM ((SELECT * FROM (PROFESSEURS JOIN CHARGE USING(NUM_PROF))) MINUS (SELECT * FROM (PROFESSEURS JOIN CHARGE USING(NUM_PROF)) WHERE NUM_COURS != 1));
/* 38 */
SELECT DISTINCT NOM FROM ELEVES NATURAL JOIN RESULTATS NATURAL JOIN (SELECT NUM_ELEVE FROM ACTIVITES_PRATIQUEES AP WHERE AP.NOM = 'Tennis') NATURAL JOIN (SELECT NUM_ELEVE FROM RESULTATS GROUP BY NUM_ELEVE HAVING AVG(POINTS) > 0.6*20) WHERE ANNEE = 1;
/* 39 */
SELECT DISTINCT NUM_PROF,NOM FROM PROFESSEURS P WHERE
    (SELECT COUNT(*) FROM (CHARGE C1 JOIN COURS C2 USING(NUM_COURS)) WHERE NUM_PROF = P.NUM_PROF AND ANNEE = 2)
    =
    (SELECT COUNT(*) FROM COURS WHERE ANNEE = 2)
;
/* 40 */
SELECT NUM_ELEVE,NOM FROM ELEVES E WHERE
    (SELECT COUNT(DISTINCT NOM) FROM (ACTIVITES_PRATIQUEES AP JOIN ACTIVITES A USING(NIVEAU,NOM)) WHERE AP.NUM_ELEVE = E.NUM_ELEVE)
    =
    (SELECT COUNT(DISTINCT NOM) FROM ACTIVITES)
;
