DROP TABLE EMPLOYE CASCADE CONSTRAINTS;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

CREATE TABLE EMPLOYE(
	NUM_EMP		NUMBER(4)		,
	NOM_EMP		VARCHAR(25)		CONSTRAINT NN_NOM_EMP NOT NULL,
	DATE_EMB		DATE			CONSTRAINT NN_DATE_EMB NOT NULL,
	DATE_SORTIE		DATE			,
	CONSTRAINT PK_EMPLOYE PRIMARY KEY (NUM_EMP)
);

INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9007,'CHEVALIER','01/01/1996');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9701,'LEROY','17/09/1997');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9703,'LAMI','17/09/1997');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9801,'SULTAN','20/03/1998');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9802,'CLEMENCE','16/10/1998');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9803,'CAVALIER','22/11/1998');
INSERT INTO EMPLOYE (NUM_EMP,NOM_EMP,DATE_EMB) VALUES(9901,'ALEXANDRE','21/02/1999');

SELECT * FROM EMPLOYE;
SELECT NOM_EMP AS NOM FROM EMPLOYE;
SELECT NOM_EMP AS NOM FROM EMPLOYE WHERE DATE_EMB >= '01/01/1999';
SELECT NUM_EMP,NOM_EMP AS NOM FROM EMPLOYE WHERE NOM_EMP LIKE 'C%';
SELECT NOM_EMP AS NOM FROM EMPLOYE ORDER BY NOM_EMP DESC;
SELECT COUNT(DATE_EMB) AS NB_EMPLOYE,EXTRACT(YEAR FROM DATE_EMB) AS ANNEE FROM EMPLOYE GROUP BY EXTRACT(YEAR FROM DATE_EMB);
SELECT COUNT(DATE_EMB) AS NB_EMPLOYE,EXTRACT(YEAR FROM DATE_EMB) AS ANNEE FROM EMPLOYE WHERE LENGTH(NOM_EMP) > 5 GROUP BY EXTRACT(YEAR FROM DATE_EMB);
SELECT COUNT(EXTRACT(YEAR FROM DATE_EMB)) AS NB_EMPLOYE,EXTRACT(YEAR FROM DATE_EMB) AS ANNEE FROM EMPLOYE WHERE (NOM_EMP LIKE 'L%' OR NOM_EMP LIKE 'C%') GROUP BY EXTRACT(YEAR FROM DATE_EMB) HAVING COUNT(EXTRACT(YEAR FROM DATE_EMB)) >= 2;
