DROP TABLE EMPLOYE CASCADE CONSTRAINTS;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

CREATE TABLE EMPLOYE(
	NumEmp		NUMBER(4)		,
	Poste			VARCHAR2(25)	CONSTRAINT NN_Poste NOT NULL,
	Salaire		NUMBER		CONSTRAINT CK_Salaire CHECK(Salaire >= 0),
	NumServ		VARCHAR2(2)		CONSTRAINT NN_NumServ NOT NULL,
	DateDeb		DATE			,
	DateFin		DATE			,
	CONSTRAINT PK_EMPLOYE PRIMARY KEY (NumEmp,DateDeb)
);

INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9701,'PRESIDENT',5800,'S2','17/09/1997');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb,DateFin) VALUES(9703,'SECRETAIRE',950,'S1','17/09/1997','31/12/1998');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9703,'SECRETAIRE',1200,'S1','01/01/1999');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb,DateFin) VALUES(9801,'DIRECTEUR',5300,'S1','07/07/1997','31/12/1998');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9801,'DIRECTEUR',3200,'S5','20/03/1998');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9802,'DIRECTEUR',3500,'S2','16/10/1998');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9803,'INGENIEUR',2600,'S4','22/11/1998');
INSERT INTO EMPLOYE (NumEmp,Poste,Salaire,NumServ,DateDeb) VALUES(9901,'DIRECTEUR',3000,'S3','21/02/1999');

SELECT DISTINCT Poste FROM EMPLOYE;
SELECT Poste,Salaire FROM EMPLOYE WHERE Salaire >= 3000;
SELECT Poste,Salaire FROM EMPLOYE WHERE Salaire >= 3000 ORDER BY Salaire DESC;
SELECT MIN(Salaire) AS SALAIRE_MIN FROM EMPLOYE;
SELECT AVG(Salaire) AS Moyenne_Salaire FROM EMPLOYE;
SELECT AVG(Salaire) AS Moyenne_Salaire,Poste AS Moyenne_Salaire_Par_Poste FROM EMPLOYE GROUP BY Poste;
SELECT COUNT(Salaire) AS Nombre_Salaire_Sup_3000 FROM EMPLOYE WHERE Salaire > 3000;
SELECT AVG(Salaire) AS Moyenne_Salaire, NumServ FROM EMPLOYE GROUP BY NumServ;
SELECT AVG(Salaire) AS Moyenne_Salaire, Poste FROM EMPLOYE GROUP BY Poste HAVING COUNT(Poste) >= 2;

